spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_HOST:jdbc:mysql://localhost:3306/db_03_products_ms}
    username: ${MYSQL_USERNAME:products-user}
    password: ${MYSQL_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect



