server:
  port: 8081

logging:
  level:
    br.com.erpsystem: DEBUG

spring:
  application:
    name: ms-comercial
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    port: ${RABBITMQ_PORT:5672}
    listener:
      simple:
        max-concurrency: 2
    connection-timeout: 1000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_HOST:jdbc:mysql://localhost:3306/db_01_cliente_ms}
    username: ${MYSQL_USERNAME:cliente-user}
    password: ${MYSQL_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect



